# Generated by Django 4.2.18 on 2025-07-13 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_contact_id', models.CharField(max_length=100)),
                ('razorpay_fund_account_id', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_last4', models.CharField(default='0000', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
