# Generated by Django 4.2.18 on 2025-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_bankingdetails_payout_delete_bankingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
