# Generated by Django 4.2.18 on 2025-08-04 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_payout_razorpay_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
