# Generated by Django 4.2.18 on 2025-08-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_bankingdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
