# Generated by Django 4.2.18 on 2025-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_delete_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
