apiVersion: v1
kind: Namespace
metadata:
  name: django-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      volumes:
        - name: static-files
          emptyDir: {}
        - name: env-volume
          secret:
            secretName: django-env-prod  # Standardized secret name
      initContainers:
        - name: django-init
          image: docker.io/ganeshjchoudhary/django-ecommerce:latest
          command: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput"]
          envFrom:
            - secretRef:
                name: django-env-prod  # Changed from django-secrets to django-env-prod
          volumeMounts:
            - name: static-files
              mountPath: /app/static
            - name: env-volume
              mountPath: /app/.env.prod
              subPath: .env.prod
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      containers:
        - name: django-app
          image: docker.io/ganeshjchoudhary/django-ecommerce:latest
          command: ["gunicorn", "ecommerce.wsgi:application", "--bind", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-env-prod  # Changed from django-secrets to django-env-prod
          volumeMounts:
            - name: static-files
              mountPath: /app/static
            - name: env-volume
              mountPath: /app/.env.prod
              subPath: .env.prod
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /healthz  # Adjust if your app has a different health endpoint
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz  # Adjust if your app has a different health endpoint
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: django-app
spec:
  selector:
    app: django-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008