apiVersion: v1
kind: Namespace
metadata:
  name: django-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      initContainers:
      - name: django-init
        image: docker.io/yourname/django-app:latest
        command: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput"]
        envFrom:
          - secretRef:
              name: django-secrets
      containers:
      - name: django-app
        image: docker.io/yourname/django-app:latest
        command: ["gunicorn", "main.wsgi:application", "--bind", "0.0.0.0:8000"]
        ports:
          - containerPort: 8000
        envFrom:
          - secretRef:
              name: django-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: django-app
spec:
  selector:
    app: django-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30008
