name: Django Code Analysis and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    name: Run Django Tests and Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies (for psycopg2 etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev gcc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit

      - name: Run flake8 (Python linting)
        run: |
          echo "Running flake8..."
          flake8 . || true  # remove '|| true' if you want linting errors to fail the build

      - name: Run Bandit (security checks)
        run: |
          echo "Running Bandit..."
          bandit -r . || true  # remove '|| true' to fail on security issues

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: ecommerce.settings  # adjust to your Django settings module
        run: |
          echo "Running Django tests..."
          python manage.py migrate --noinput
          python manage.py test || echo "No tests found or some tests failed."
